/* SHARED DATA — single source of truth used by Home, AIBPOPage, ServicePage */
export const SERVICES = [
  {
    id: 'customer-care',
    tag: 'CX AI',
    tagVariant: 'amber',
    icon: 'Headphones',
    title: 'AI Customer Care',
    short: 'Resolve 90% of queries instantly across voice, chat and email — 24/7, in 120+ languages, with zero wait times.',
    hero: 'The End of Waiting.',
    heroSub: 'AI-powered customer care that never sleeps, never gets frustrated, and resolves 90% of queries on first contact.',
    color: 'amber',
    stat1: { n: '90%', l: 'First-Contact Resolution' },
    stat2: { n: '< 1s', l: 'Average Response Time' },
    why: [
      { title: '24/7 Availability', desc: 'No shifts, no breaks, no overtime. Your customers get instant responses at 3am on a Sunday.' },
      { title: '120+ Languages', desc: 'Native multilingual processing — not translation. Every customer feels understood in their own language.' },
      { title: '85% Cost Reduction', desc: 'Eliminate the cost of large support teams while dramatically improving satisfaction scores.' },
      { title: 'Omnichannel', desc: 'One AI brain across voice, live chat, email, WhatsApp, and social media simultaneously.' },
    ],
    sectors: ['E-Commerce', 'Telecom', 'Banking', 'Healthcare', 'SaaS', 'Retail'],
    flow: ['Customer Query', 'Intent Detection', 'Context Retrieval', 'Resolution Engine', 'Response & Follow-up'],
  },
  {
    id: 'hr-automation',
    tag: 'HR Ops',
    tagVariant: 'violet',
    icon: 'Users',
    title: 'AI HR & Talent Ops',
    short: 'Full-cycle recruitment and HR operations — sourcing, screening, scheduling, onboarding — with zero HR headcount.',
    hero: 'Hire Faster. Onboard Better.',
    heroSub: 'Tevrix AI automates the entire HR lifecycle — from job posting to day-90 check-ins — without a single HR hire.',
    color: 'violet',
    stat1: { n: '10×', l: 'Faster Hiring Cycle' },
    stat2: { n: '60%', l: 'Reduction in HR Costs' },
    why: [
      { title: 'Automated Sourcing', desc: 'AI scans thousands of profiles against your job requirements and ranks top candidates in minutes.' },
      { title: 'Intelligent Screening', desc: 'Structured phone/video interviews conducted by AI with full transcripts and scoring.' },
      { title: 'Smart Scheduling', desc: 'Calendar coordination with candidates and interviewers, automated reminders, and rescheduling.' },
      { title: 'Onboarding Automation', desc: 'Document collection, compliance checks, and onboarding workflows handled end-to-end.' },
    ],
    sectors: ['Staffing Firms', 'Enterprise', 'Healthcare', 'Retail (Volume Hiring)', 'IT Companies'],
    flow: ['Job Requisition', 'AI Sourcing', 'Screening Interview', 'Shortlist & Schedule', 'Offer & Onboard'],
  },
  {
    id: 'financial-analyst',
    tag: 'FinOps',
    tagVariant: 'amber',
    icon: 'BarChart3',
    title: 'AI Financial Analyst',
    short: 'Real-time bookkeeping, invoice processing, audit preparation, and financial forecasting — no finance department needed.',
    hero: 'Finance, Automated.',
    heroSub: 'AI that reads your financials, flags anomalies, processes invoices, and prepares audit-ready reports in real time.',
    color: 'amber',
    stat1: { n: '99.8%', l: 'Accuracy Rate' },
    stat2: { n: '80%', l: 'Finance Cost Reduction' },
    why: [
      { title: 'Automated Bookkeeping', desc: 'Every transaction categorized, reconciled, and posted in real time without human input.' },
      { title: 'Invoice Intelligence', desc: 'Extract, validate, and approve invoices — handling exceptions automatically.' },
      { title: 'Audit Readiness', desc: 'Always audit-ready documentation with complete chain of custody on every financial event.' },
      { title: 'Anomaly Detection', desc: 'Flags unusual patterns, potential fraud, and compliance risks before they become problems.' },
    ],
    sectors: ['Banking', 'Accounting Firms', 'E-Commerce', 'Healthcare', 'Logistics', 'Manufacturing'],
    flow: ['Data Ingestion', 'Transaction Parsing', 'Categorization & Rules', 'Reconciliation', 'Report Generation'],
  },
  {
    id: 'document-intelligence',
    tag: 'Doc AI',
    tagVariant: 'amber',
    icon: 'FileText',
    title: 'Document Intelligence',
    short: 'Contracts, compliance docs, reports — extracted, classified, and routed automatically across your enterprise stack.',
    hero: 'Documents That Think.',
    heroSub: 'Unstructured documents become structured intelligence — extracted, verified, and acted upon in milliseconds.',
    color: 'amber',
    stat1: { n: '10M+', l: 'Documents Processed Daily' },
    stat2: { n: '99%', l: 'Extraction Accuracy' },
    why: [
      { title: 'Universal Parsing', desc: 'PDFs, Word docs, scanned images, handwritten forms — processed with equal accuracy.' },
      { title: 'Smart Classification', desc: 'Documents auto-tagged, routed to right teams, and filed correctly without human review.' },
      { title: 'Compliance Engine', desc: 'Identifies regulatory clauses, expiry dates, and required fields across contract libraries.' },
      { title: 'ERP Integration', desc: 'Direct integration with SAP, Oracle, Salesforce and 200+ enterprise systems.' },
    ],
    sectors: ['Legal Firms', 'Insurance', 'Real Estate', 'Banking', 'Government', 'Healthcare'],
    flow: ['Document Intake', 'OCR & Parsing', 'AI Classification', 'Data Extraction', 'Route & Archive'],
  },
  {
    id: 'voice-ai',
    tag: 'Voice AI',
    tagVariant: 'violet',
    icon: 'Phone',
    title: 'AI Reception & Voice',
    short: 'Inbound and outbound calls handled by voice AI with human-level empathy, across 120+ languages, 24/7.',
    hero: 'Every Call. Handled.',
    heroSub: 'Voice AI that sounds human, thinks intelligently, and resolves calls without ever putting a customer on hold.',
    color: 'violet',
    stat1: { n: '10K+', l: 'Simultaneous Calls' },
    stat2: { n: '0ms', l: 'You are in the Right Place' },
    why: [
      { title: 'Human-Quality Voice', desc: 'Natural speech synthesis indistinguishable from a trained agent, with emotional adapt.' },
      { title: 'Real-Time Intent', desc: 'Understands caller intent mid-sentence and responds appropriately without scripts.' },
      { title: 'Outbound Campaigns', desc: 'Run thousands of personalized outbound calls simultaneously for collections, surveys, or appointments.' },
      { title: 'CRM Sync', desc: 'Every call logged, transcribed, and synced to your CRM with full summary and action items.' },
    ],
    sectors: ['Healthcare (Appointment)', 'Banking (Collections)', 'E-Commerce (Order Updates)', 'Telecom', 'Insurance'],
    flow: ['Incoming Call', 'Voice-to-Text (STT)', 'Intent Recognition', 'Response Generation', 'Text-to-Speech (TTS)'],
  },
  {
    id: 'custom-process',
    tag: 'Custom',
    tagVariant: 'violet',
    icon: 'Layers',
    title: 'Custom Process Design',
    short: 'Every company has unique workflows. Our AI architects map, learn, and automate your specific processes in weeks.',
    hero: 'Your Process. Automated.',
    heroSub: 'Tevrix AI architects study your operations and build bespoke AI agents that replace your most expensive workflows.',
    color: 'violet',
    stat1: { n: '6wks', l: 'Average Deployment Time' },
    stat2: { n: '3×', l: 'ROI in Year One' },
    why: [
      { title: 'Process Discovery', desc: 'Our AI architects shadow your team digitally, mapping every step of your current workflows.' },
      { title: 'Agent Design', desc: 'Custom AI agents built for each process, not generic solutions shoehorned into your stack.' },
      { title: 'Integration First', desc: 'Built to connect with your existing tools — no rip-and-replace required.' },
      { title: 'Continuous Learning', desc: 'Agents improve over time from feedback, edge cases, and new business rules.' },
    ],
    sectors: ['Any Industry', 'Unique Operations', 'High-Volume Back Office', 'Compliance-Heavy Sectors'],
    flow: ['Discovery Sprint', 'Process Mapping', 'Agent Architecture', 'Integration & QA', 'Deployment & Monitor'],
  },
];

export const SECTORS = [
  { name: 'E-Commerce', icon: '🛒', desc: 'Returns, order updates, CX at scale.' },
  { name: 'Healthcare', icon: '🏥', desc: 'Appointments, records, billing.' },
  { name: 'Banking & Finance', icon: '🏦', desc: 'Collections, KYC, support.' },
  { name: 'Telecom', icon: '📡', desc: 'Plan changes, technical support.' },
  { name: 'Insurance', icon: '🛡️', desc: 'Claims, renewals, underwriting.' },
  { name: 'Logistics', icon: '📦', desc: 'Tracking, exceptions, coordination.' },
  { name: 'Real Estate', icon: '🏢', desc: 'Lead qualification, scheduling.' },
  { name: 'Education', icon: '🎓', desc: 'Admissions, support, compliance.' },
];

export const BPO_STATS = [
  { n: '500+',  l: 'Enterprise Clients' },
  { n: '99.9%', l: 'Accuracy Rate' },
  { n: '120+',  l: 'Languages Supported' },
  { n: '< 1ms', l: 'Response Latency' },
  { n: '$280B', l: 'Market We\'re Disrupting' },
  { n: '85%',   l: 'Cost vs. Traditional BPO' },
  { n: '24/7',  l: 'Always On' },
  { n: '10K+',  l: 'Concurrent AI Calls' },
  { n: '6 wks', l: 'Avg. Deployment Time' },
  { n: '3×',    l: 'Avg. Year-1 ROI' },
];
