/* SHARED DATA — single source of truth used by Home, AIBPOPage, ServicePage */
export const SERVICES = [
  {
    id: 'customer-care',
    tag: 'CX AI',
    tagVariant: 'amber',
    icon: 'Headphones',
    title: 'AI Customer Care',
    short: 'Resolve 90% of queries instantly across voice, chat and email — 24/7, in 120+ languages, with zero wait times.',
    hero: 'The End of Waiting.',
    heroSub: 'AI-powered customer care that never sleeps, never gets frustrated, and resolves 90% of queries on first contact.',
    color: 'amber',
    stat1: { n: '90%', l: 'First-Contact Resolution' },
    stat2: { n: '< 1s', l: 'Average Response Time' },
    why: [
      { title: '24/7 Availability', desc: 'No shifts, no breaks, no overtime. Your customers get instant responses at 3am on a Sunday.' },
      { title: '120+ Languages', desc: 'Native multilingual processing — not translation. Every customer feels understood in their own language.' },
      { title: '85% Cost Reduction', desc: 'Eliminate the cost of large support teams while dramatically improving satisfaction scores.' },
      { title: 'Omnichannel', desc: 'One AI brain across voice, live chat, email, WhatsApp, and social media simultaneously.' },
    ],
    sectors: ['E-Commerce', 'Telecom', 'Banking', 'Healthcare', 'SaaS', 'Retail'],
    flow: ['Customer Query', 'Intent Detection', 'Context Retrieval', 'Resolution Engine', 'Response & Follow-up'],
    costSaving: {
      items: [
        { label: 'Traditional call center agent', value: '₹200/hr', strike: true },
        { label: 'Tevrix AI Customer Care', value: '₹50/hr', highlight: true },
        { label: 'No shifts, no overtime, no attrition', value: '24/7', accent: true },
      ],
      saving: '75%',
      savingLabel: 'cost reduction vs. traditional BPO',
    },
  },
  {
    id: 'hr-automation',
    tag: 'AI HR',
    tagVariant: 'violet',
    icon: 'Users',
    title: 'AI HR & Talent Ops',
    launchBadge: 'Launching Next Month · Open Signup',
    ctaLabel: 'Get Early Access',
    short: 'From job description to top 5 shortlisted candidates — AI that parses 1000s of CVs, runs proctored assessments, conducts AI interviews, and ranks candidates with scores and reasoning.',
    problemStatement: {
      headline: 'Hiring is Broken.',
      sub: 'Every company that hires is losing time, money, and the best candidates to a process designed for the 1990s.',
      stats: [
        { n: '250+', l: 'CVs per job post on average', detail: 'Most are never read by a human recruiter' },
        { n: '42 days', l: 'Average time-to-hire', detail: 'Your best candidates accept elsewhere in week two' },
        { n: '70%', l: 'Recruiter time wasted', detail: 'Spent screening, scheduling, and taking notes — not hiring' },
        { n: '₹1L+', l: 'Average cost-per-hire in India', detail: 'Before onboarding costs, missed productivity, and bad hires' },
      ],
      insight: 'The problem isn\'t finding talent. It\'s that recruiters spend most of their day on tasks that have nothing to do with judgement. Tevrix AI takes everything that can be automated — and automates it completely.',
    },
    hero: 'Your AI Hiring Team. Always On.',
    heroSub: 'Tevrix AI runs the entire hiring pipeline autonomously — so your team only spends time with the best 5 candidates.',
    color: 'violet',
    stat1: { n: '1000s', l: 'CVs Parsed Simultaneously' },
    stat2: { n: 'Top 5', l: 'Candidates Scored & Ranked' },
    features: [
      { icon: 'FileText', title: 'AI Job Description Generator', desc: 'Generate precise, bias-free JDs tailored to your role, team, and hiring bar — in seconds.' },
      { icon: 'ScanSearch', title: 'CV Parsing at Scale', desc: 'Parse thousands of CVs simultaneously, extract structured data, and rank candidates against your JD criteria automatically.' },
      { icon: 'Code2', title: 'Proctored Coding Challenges', desc: 'Built-in coding assessments with real-time proctoring. Candidates are monitored and scored without any third-party tool.' },
      { icon: 'Video', title: 'AI Proctored Video Interviews', desc: 'AI conducts structured video interviews, monitors for integrity violations, and records every session with a full transcript.' },
      { icon: 'FileSearch', title: 'Interview Transcript & Summary', desc: 'Every interview is automatically transcribed, summarised, and scored against your role criteria — no manual note-taking.' },
      { icon: 'Trophy', title: 'Top 5 Candidate Shortlist', desc: 'AI delivers a ranked shortlist of the top 5 candidates with individual scores, reasoned evaluations, and side-by-side comparisons.' },
      { icon: 'MessageSquare', title: 'Recruiter AI Chatbot', desc: "Ask your AI: 'Compare candidate A vs B', 'What's on my interview list today?', 'Summarise this transcript.' Always available, always instant." },
    ],
    why: [
      { title: 'End-to-End, Not a Point Tool', desc: 'JD generation → CV parsing → coding tests → AI interviews → shortlist. One system, zero stitching, no manual handoffs between steps.' },
      { title: 'Proctored at Every Stage', desc: 'Built-in integrity monitoring across coding challenges and video interviews — no third-party proctoring tools required.' },
      { title: 'Score + Reasoning, Not Just a Number', desc: 'Recruiters see ranked candidates with individual scores, AI-written evaluation summaries, and direct transcript evidence — not black-box rankings.' },
      { title: 'Built In-House on Latest AI Models', desc: 'Every component is built by Tevrix on a multi-agentic architecture using the latest models — faster, smarter, and continuously improving.' },
    ],
    sectors: ['Startups', 'Scale-ups', 'Enterprise HR Teams', 'IT & Tech Companies', 'Staffing Firms', 'Any Company That Hires'],
    flow: ['AI Job Description', 'CV Parsing (1000s)', 'Coding Assessment', 'AI Proctored Interview', 'Score & Shortlist Top 5'],
    costSaving: {
      items: [
        { label: 'Average cost-per-hire (India)', value: '₹1L+', strike: true },
        { label: 'With Tevrix AI HR', value: '<₹5,000', highlight: true },
        { label: 'Recruiter hours saved per hire', value: '40+ hrs', accent: true },
      ],
      saving: '95%',
      savingLabel: 'cost-per-hire reduction on subscription',
    },
  },
  {
    id: 'financial-analyst',
    tag: 'FinOps',
    tagVariant: 'amber',
    icon: 'BarChart3',
    title: 'AI Financial Analyst',
    short: 'Real-time bookkeeping, invoice processing, audit preparation, and financial forecasting — no finance department needed.',
    hero: 'Finance, Automated.',
    heroSub: 'AI that reads your financials, flags anomalies, processes invoices, and prepares audit-ready reports in real time.',
    color: 'amber',
    stat1: { n: '99.8%', l: 'Accuracy Rate' },
    stat2: { n: '80%', l: 'Finance Cost Reduction' },
    why: [
      { title: 'Automated Bookkeeping', desc: 'Every transaction categorized, reconciled, and posted in real time without human input.' },
      { title: 'Invoice Intelligence', desc: 'Extract, validate, and approve invoices — handling exceptions automatically.' },
      { title: 'Audit Readiness', desc: 'Always audit-ready documentation with complete chain of custody on every financial event.' },
      { title: 'Anomaly Detection', desc: 'Flags unusual patterns, potential fraud, and compliance risks before they become problems.' },
    ],
    sectors: ['Banking', 'Accounting Firms', 'E-Commerce', 'Healthcare', 'Logistics', 'Manufacturing'],
    flow: ['Data Ingestion', 'Transaction Parsing', 'Categorization & Rules', 'Reconciliation', 'Report Generation'],
    costSaving: {
      items: [
        { label: 'In-house finance team (3 people)', value: '₹4L/mo', strike: true },
        { label: 'Tevrix AI Financial Analyst', value: '₹50,000/mo', highlight: true },
        { label: 'Zero overtime, zero errors from fatigue', value: '99.8%', accent: true },
      ],
      saving: '80%',
      savingLabel: 'finance operations cost reduction',
    },
  },
  {
    id: 'document-intelligence',
    tag: 'Doc AI',
    tagVariant: 'amber',
    icon: 'FileText',
    title: 'Document Intelligence',
    short: 'Contracts, compliance docs, reports — extracted, classified, and routed automatically across your enterprise stack.',
    hero: 'Documents That Think.',
    heroSub: 'Unstructured documents become structured intelligence — extracted, verified, and acted upon in milliseconds.',
    color: 'amber',
    stat1: { n: '10M+', l: 'Documents Processed Daily' },
    stat2: { n: '99%', l: 'Extraction Accuracy' },
    why: [
      { title: 'Universal Parsing', desc: 'PDFs, Word docs, scanned images, handwritten forms — processed with equal accuracy.' },
      { title: 'Smart Classification', desc: 'Documents auto-tagged, routed to right teams, and filed correctly without human review.' },
      { title: 'Compliance Engine', desc: 'Identifies regulatory clauses, expiry dates, and required fields across contract libraries.' },
      { title: 'ERP Integration', desc: 'Direct integration with SAP, Oracle, Salesforce and 200+ enterprise systems.' },
    ],
    sectors: ['Legal Firms', 'Insurance', 'Real Estate', 'Banking', 'Government', 'Healthcare'],
    flow: ['Document Intake', 'OCR & Parsing', 'AI Classification', 'Data Extraction', 'Route & Archive'],
    costSaving: {
      items: [
        { label: 'Manual document processing', value: '₹150/hr', strike: true },
        { label: 'Tevrix AI Document Intelligence', value: '₹12/hr', highlight: true },
        { label: 'Accuracy vs. manual (error-prone)', value: '99% vs 82%', accent: true },
      ],
      saving: '92%',
      savingLabel: 'cost reduction vs. manual processing',
    },
  },
  {
    id: 'voice-ai',
    tag: 'Voice AI',
    tagVariant: 'violet',
    icon: 'Phone',
    title: 'AI Reception & Voice',
    short: 'AI receptionist that handles inbound calls, books appointments, manages scheduling, and integrates with WhatsApp — powered by realtime multimodal AI for zero-latency conversations.',
    hero: 'Every Call. Booked.',
    heroSub: 'A 24/7 AI receptionist that picks up every call, schedules appointments, and handles WhatsApp — powered by realtime multimodal AI, not a traditional STT/TTS pipeline.',
    color: 'violet',
    stat1: { n: '10K+', l: 'Simultaneous Calls' },
    stat2: { n: '<200ms', l: 'End-to-End Response Latency' },
    why: [
      { title: 'Realtime Multimodal AI', desc: 'No traditional STT → NLP → TTS pipeline. Native audio understanding and generation with sub-200ms latency — conversations feel instant and natural.' },
      { title: 'Bookings & Scheduling', desc: 'Callers can book, reschedule, or cancel appointments directly over the phone. Slots synced to your calendar in real time — zero manual intervention.' },
      { title: 'WhatsApp Integration', desc: 'The same AI receptionist handles WhatsApp messages: confirmations, reminders, rescheduling, and FAQs — same logic, same knowledge, both channels.' },
      { title: 'CRM & Calendar Sync', desc: 'Every call and WhatsApp interaction is logged with a full summary and action items, synced to your CRM and booking system automatically.' },
    ],
    sectors: ['Clinics & Healthcare', 'Salons & Wellness', 'Real Estate', 'Legal Firms', 'Restaurants', 'Any Business That Takes Appointments'],
    flow: ['Call / WhatsApp', 'Realtime Audio Processing', 'Intent & Slot Detection', 'Booking / Response', 'Calendar & CRM Sync'],
    costSaving: {
      items: [
        { label: 'Human receptionist (full-time)', value: '₹25,000/mo', strike: true },
        { label: 'Tevrix AI Receptionist', value: '₹5,000/mo', highlight: true },
        { label: 'Handles calls + WhatsApp 24/7', value: '24/7', accent: true },
      ],
      saving: '80%',
      savingLabel: 'cost reduction vs. full-time receptionist',
    },
  },
  {
    id: 'custom-process',
    tag: 'Custom',
    tagVariant: 'violet',
    icon: 'Layers',
    title: 'Custom Process Design',
    short: 'Every company has unique workflows. Our AI architects map, learn, and automate your specific processes in weeks.',
    hero: 'Your Process. Automated.',
    heroSub: 'Tevrix AI architects study your operations and build bespoke AI agents that replace your most expensive workflows.',
    color: 'violet',
    stat1: { n: '6wks', l: 'Average Deployment Time' },
    stat2: { n: '3×', l: 'ROI in Year One' },
    why: [
      { title: 'Process Discovery', desc: 'Our AI architects shadow your team digitally, mapping every step of your current workflows.' },
      { title: 'Agent Design', desc: 'Custom AI agents built for each process, not generic solutions shoehorned into your stack.' },
      { title: 'Integration First', desc: 'Built to connect with your existing tools — no rip-and-replace required.' },
      { title: 'Continuous Learning', desc: 'Agents improve over time from feedback, edge cases, and new business rules.' },
    ],
    sectors: ['Any Industry', 'Unique Operations', 'High-Volume Back Office', 'Compliance-Heavy Sectors'],
    flow: ['Discovery Sprint', 'Process Mapping', 'Agent Architecture', 'Integration & QA', 'Deployment & Monitor'],
    costSaving: {
      items: [
        { label: 'Current process (human team)', value: 'Baseline', strike: true },
        { label: 'After Tevrix custom automation', value: '-60–90%', highlight: true },
        { label: 'Average year-one ROI', value: '3×', accent: true },
      ],
      saving: '3×',
      savingLabel: 'average ROI in year one',
    },
  },
];

export const SECTORS = [
  { name: 'E-Commerce', icon: '🛒', desc: 'Returns, order updates, CX at scale.' },
  { name: 'Healthcare', icon: '🏥', desc: 'Appointments, records, billing.' },
  { name: 'Banking & Finance', icon: '🏦', desc: 'Collections, KYC, support.' },
  { name: 'Telecom', icon: '📡', desc: 'Plan changes, technical support.' },
  { name: 'Insurance', icon: '🛡️', desc: 'Claims, renewals, underwriting.' },
  { name: 'Logistics', icon: '📦', desc: 'Tracking, exceptions, coordination.' },
  { name: 'Real Estate', icon: '🏢', desc: 'Lead qualification, scheduling.' },
  { name: 'Education', icon: '🎓', desc: 'Admissions, support, compliance.' },
];

export const BPO_STATS = [
  { n: 'Jan \'26', l: 'India Founded' },
  { n: '99.9%', l: 'Accuracy Rate' },
  { n: '120+',  l: 'Languages Supported' },
  { n: '< 1ms', l: 'Response Latency' },
  { n: '$280B', l: 'Market We\'re Disrupting' },
  { n: '85%',   l: 'Cost vs. Traditional BPO' },
  { n: '24/7',  l: 'Always On' },
  { n: '10K+',  l: 'Concurrent AI Calls' },
  { n: '6 wks', l: 'Avg. Deployment Time' },
  { n: '3×',    l: 'Avg. Year-1 ROI' },
  { n: '₹50/hr', l: 'vs ₹200/hr Human Agent' },
  { n: '₹0',    l: 'Night Shift Premium' },
];
